total_images: 9

specifications:
  # Test 1: Uniform black (backward compatible)
  - name: "uniform_black"
    proportion: 0.33
    text_direction: "left_to_right"
    corpus_file: "gutenberg_11.txt"
    color_mode: "uniform"
    text_color_min: [0, 0, 0]
    text_color_max: [0, 0, 0]
    min_text_length: 10
    max_text_length: 20

  # Test 2: Uniform red text
  - name: "uniform_red"
    proportion: 0.33
    text_direction: "left_to_right"
    corpus_file: "gutenberg_11.txt"
    color_mode: "uniform"
    text_color_min: [200, 0, 0]
    text_color_max: [255, 50, 50]
    min_text_length: 10
    max_text_length: 20

  # Test 3: Gradient blue to yellow
  - name: "gradient_blue_yellow"
    proportion: 0.34
    text_direction: "left_to_right"
    corpus_file: "gutenberg_11.txt"
    color_mode: "gradient"
    gradient_start_color_min: [0, 0, 255]
    gradient_start_color_max: [0, 0, 255]
    gradient_end_color_min: [255, 255, 0]
    gradient_end_color_max: [255, 255, 0]
    min_text_length: 10
    max_text_length: 20
