total_images: 10000

specifications:
  # Spec 1: Basic LTR with moderate effects
  - name: ltr_moderate_effects
    proportion: 0.3
    text_direction: left_to_right
    corpus_file: "gutenberg_1116.txt"
    min_text_length: 15
    max_text_length: 50
    rotation_angle_min: -5.0
    rotation_angle_max: 5.0
    noise_amount_min: 0.0
    noise_amount_max: 0.02
    blur_radius_min: 0.0
    blur_radius_max: 1.5
    brightness_factor_min: 0.85
    brightness_factor_max: 1.15
    contrast_factor_min: 0.85
    contrast_factor_max: 1.15

  # Spec 2: High variation effects
  - name: ltr_high_variation
    proportion: 0.2
    text_direction: left_to_right
    corpus_file: "gutenberg_1116.txt"
    min_text_length: 10
    max_text_length: 80
    rotation_angle_min: -15.0
    rotation_angle_max: 15.0
    noise_amount_min: 0.0
    noise_amount_max: 0.05
    blur_radius_min: 0.0
    blur_radius_max: 3.0
    brightness_factor_min: 0.7
    brightness_factor_max: 1.3
    contrast_factor_min: 0.7
    contrast_factor_max: 1.3

  # Spec 3: Minimal effects (clean images)
  - name: ltr_clean
    proportion: 0.2
    text_direction: left_to_right
    corpus_file: "gutenberg_1116.txt"
    min_text_length: 20
    max_text_length: 60
    rotation_angle_min: -2.0
    rotation_angle_max: 2.0
    noise_amount_min: 0.0
    noise_amount_max: 0.005
    blur_radius_min: 0.0
    blur_radius_max: 0.5
    brightness_factor_min: 0.95
    brightness_factor_max: 1.05
    contrast_factor_min: 0.95
    contrast_factor_max: 1.05

  # Spec 4: Short text with heavy effects
  - name: ltr_short_heavy
    proportion: 0.15
    text_direction: left_to_right
    corpus_file: "gutenberg_1116.txt"
    min_text_length: 5
    max_text_length: 25
    rotation_angle_min: -20.0
    rotation_angle_max: 20.0
    noise_amount_min: 0.01
    noise_amount_max: 0.08
    blur_radius_min: 0.5
    blur_radius_max: 4.0
    brightness_factor_min: 0.6
    brightness_factor_max: 1.4
    contrast_factor_min: 0.6
    contrast_factor_max: 1.4

  # Spec 5: Long text minimal effects
  - name: ltr_long_clean
    proportion: 0.15
    text_direction: left_to_right
    corpus_file: "gutenberg_1116.txt"
    min_text_length: 60
    max_text_length: 120
    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
