# Stage 2 Demo: LTR Multi-Line Features - Intermediate
# This configuration demonstrates:
# 1. Different text alignments (left, center, right)
# 2. Variable line spacing
# 3. Multi-line with effects applied uniformly

total_images: 150

specifications:
  # Spec 1: Left alignment with effects - 33%
  - name: "ltr_multiline_left_aligned"
    proportion: 0.33
    text_direction: "left_to_right"
    corpus_file: "ltr/gutenberg_11.txt"

    min_text_length: 40
    max_text_length: 120
    min_lines: 2
    max_lines: 5
    line_break_mode: "word"
    line_spacing_min: 1.0
    line_spacing_max: 1.5
    text_alignment: "left"

    font_size_min: 28
    font_size_max: 48

    # Drop shadow for depth
    drop_shadow_offset_x_min: 2
    drop_shadow_offset_x_max: 5
    drop_shadow_offset_y_min: 2
    drop_shadow_offset_y_max: 5
    drop_shadow_radius_min: 1.0
    drop_shadow_radius_max: 3.0
    drop_shadow_color_min: [0, 0, 0, 150]
    drop_shadow_color_max: [0, 0, 0, 200]

    # Add some effects (applied uniformly to all lines)
    noise_amount_min: 0.0
    noise_amount_max: 0.1
    blur_radius_min: 0.0
    blur_radius_max: 0.5
    rotation_angle_min: -5.0
    rotation_angle_max: 5.0

    # Keep other effects minimal
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    brightness_factor_min: 0.9
    brightness_factor_max: 1.1
    contrast_factor_min: 0.9
    contrast_factor_max: 1.1
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 2: Center alignment with variable spacing - 33%
  - name: "ltr_multiline_center_aligned"
    proportion: 0.33
    text_direction: "left_to_right"
    corpus_file: "ltr/gutenberg_1116.txt"

    min_text_length: 50
    max_text_length: 150
    min_lines: 3
    max_lines: 6
    line_break_mode: "word"
    line_spacing_min: 1.2
    line_spacing_max: 2.0
    line_spacing_distribution: "uniform"
    text_alignment: "center"

    font_size_min: 24
    font_size_max: 40

    # Per-glyph color palette with 2-3 colors cycling through text
    color_mode: "per_glyph"
    per_glyph_palette_size_min: 2
    per_glyph_palette_size_max: 3
    text_color_min: [20, 20, 20]
    text_color_max: [80, 80, 80]

    # Different effects
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 1.0
    rotation_angle_min: 0.0
    rotation_angle_max: 0.0

    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 3: Right alignment with character breaking - 34%
  - name: "ltr_multiline_right_aligned"
    proportion: 0.34
    text_direction: "left_to_right"
    corpus_file: "ltr/gutenberg_15.txt"

    min_text_length: 30
    max_text_length: 90
    min_lines: 2
    max_lines: 4
    line_break_mode: "character"
    line_spacing_min: 1.0
    line_spacing_max: 1.3
    text_alignment: "right"

    font_size_min: 32
    font_size_max: 52

    # Block shadow for subtle effect
    block_shadow_offset_x_min: 1
    block_shadow_offset_x_max: 3
    block_shadow_offset_y_min: 1
    block_shadow_offset_y_max: 3
    block_shadow_radius_min: 0.5
    block_shadow_radius_max: 2.0
    block_shadow_color_min: [100, 100, 100, 100]
    block_shadow_color_max: [150, 150, 150, 150]

    # Perspective warp (uniform across all lines)
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.05

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0
