# Stage 2 Demo: BTT Multi-Line Features - Intermediate

total_images: 150

specifications:
  # Spec 1: Bottom alignment with effects
  - name: "btt_multiline_bottom_aligned"
    proportion: 0.33
    text_direction: "bottom_to_top"
    corpus_file: "ltr/gutenberg_11.txt"

    min_text_length: 20
    max_text_length: 60
    min_lines: 2
    max_lines: 4
    line_break_mode: "character"
    line_spacing_min: 1.2
    line_spacing_max: 1.8
    text_alignment: "bottom"

    font_size_min: 28
    font_size_max: 48

    noise_amount_min: 0.0
    noise_amount_max: 0.1
    blur_radius_min: 0.0
    blur_radius_max: 0.5
    rotation_angle_min: -5.0
    rotation_angle_max: 5.0

    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    brightness_factor_min: 0.9
    brightness_factor_max: 1.1
    contrast_factor_min: 0.9
    contrast_factor_max: 1.1
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 2: Center alignment with variable spacing
  - name: "btt_multiline_center_aligned"
    proportion: 0.33
    text_direction: "bottom_to_top"
    corpus_file: "ltr/gutenberg_1116.txt"

    min_text_length: 25
    max_text_length: 70
    min_lines: 3
    max_lines: 5
    line_break_mode: "word"
    line_spacing_min: 1.5
    line_spacing_max: 2.5
    text_alignment: "center"

    font_size_min: 24
    font_size_max: 40

    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 1.0

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 3: Top alignment with perspective warp
  - name: "btt_multiline_top_aligned"
    proportion: 0.34
    text_direction: "bottom_to_top"
    corpus_file: "ltr/gutenberg_15.txt"

    min_text_length: 15
    max_text_length: 45
    min_lines: 2
    max_lines: 4
    line_break_mode: "character"
    line_spacing_min: 1.2
    line_spacing_max: 1.6
    text_alignment: "top"

    font_size_min: 32
    font_size_max: 52

    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.05

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0
