# Stage 1 Demo: RTL Multi-Line Features - Basic
# Demonstrates multi-line features for right-to-left text

total_images: 150

specifications:
  # Spec 1: Single-line RTL (backward compatibility)
  - name: "rtl_single_line_compat"
    proportion: 0.33
    text_direction: "right_to_left"
    corpus_file: "ltr/gutenberg_11.txt"  # Using LTR corpus for demo

    min_text_length: 10
    max_text_length: 30
    min_lines: 1
    max_lines: 1

    font_size_min: 32
    font_size_max: 48

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 2: Multi-line RTL with word breaking
  - name: "rtl_multiline_word"
    proportion: 0.33
    text_direction: "right_to_left"
    corpus_file: "ltr/gutenberg_1116.txt"

    min_text_length: 30
    max_text_length: 100
    min_lines: 2
    max_lines: 4
    line_break_mode: "word"
    line_spacing_min: 1.0
    line_spacing_max: 1.5
    text_alignment: "right"  # Natural alignment for RTL

    font_size_min: 28
    font_size_max: 40

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0

  # Spec 3: Multi-line RTL with character breaking
  - name: "rtl_multiline_char"
    proportion: 0.34
    text_direction: "right_to_left"
    corpus_file: "ltr/gutenberg_15.txt"

    min_text_length: 30
    max_text_length: 80
    min_lines: 3
    max_lines: 5
    line_break_mode: "character"
    line_spacing_min: 1.2
    line_spacing_max: 1.8
    text_alignment: "center"

    font_size_min: 24
    font_size_max: 36

    rotation_angle_min: 0.0
    rotation_angle_max: 0.0
    curve_type: "none"
    glyph_overlap_intensity_min: 0.0
    glyph_overlap_intensity_max: 0.0
    ink_bleed_radius_min: 0.0
    ink_bleed_radius_max: 0.0
    perspective_warp_magnitude_min: 0.0
    perspective_warp_magnitude_max: 0.0
    noise_amount_min: 0.0
    noise_amount_max: 0.0
    blur_radius_min: 0.0
    blur_radius_max: 0.0
    brightness_factor_min: 1.0
    brightness_factor_max: 1.0
    contrast_factor_min: 1.0
    contrast_factor_max: 1.0
    elastic_distortion_alpha_min: 0.0
    elastic_distortion_alpha_max: 0.0
    elastic_distortion_sigma_min: 0.0
    elastic_distortion_sigma_max: 0.0
    grid_distortion_steps_min: 0
    grid_distortion_steps_max: 0
    grid_distortion_limit_min: 0.0
    grid_distortion_limit_max: 0.0
    optical_distortion_limit_min: 0.0
    optical_distortion_limit_max: 0.0
    erosion_dilation_kernel_min: 0
    erosion_dilation_kernel_max: 0
    cutout_width_min: 0
    cutout_width_max: 0
    cutout_height_min: 0
    cutout_height_max: 0
